# Generated by Django 6.1.1 on 2026-10-02 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Sualın mətni')),
                ('points', models.FloatField(default=1.0, verbose_name='Sualın maks balı')),
                ('question_type', models.CharField(choices=[('test', 'Test (A-D)'), ('written', 'Yazılı'), ('code', 'Proqramlaşdırma (Kod)')], default='test', max_length=20)),
                ('option_a', models.CharField(blank=True, max_length=255, null=True)),
                ('option_b', models.CharField(blank=True, max_length=255, null=True)),
                ('option_c', models.CharField(blank=True, max_length=255, null=True)),
                ('option_d', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_option', models.CharField(blank=True, help_text='A, B, C və ya D', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='İmtahan adı')),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='Müddət (dəqiqə)')),
                ('max_warnings', models.IntegerField(default=3, verbose_name='Maksimum xəbərdarlıq limiti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Bilet adı (Məs: Bilet 1)')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.exam')),
                ('questions', models.ManyToManyField(related_name='tickets', to='core.question')),
            ],
        ),
    ]
