# Generated by Django 6.1.1 on 2026-10-05 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_question_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='questions_per_student',
            field=models.PositiveIntegerField(default=10, verbose_name='Hər tələbəyə düşən sual sayı'),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Başlama vaxtı'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='student_groups', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='exams', to='core.group', verbose_name='Qruplar'),
        ),
    ]
