# Generated by Django 6.1.1 on 2026-10-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_exam_questions_per_student_exam_start_time_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('test', 'Test'), ('written', 'Yazılı')], default='test', max_length=10, verbose_name='İmtahan növü'),
        ),
    ]
